[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; --- Optimize Upload ---
upload_protocol = esptool







upload_speed = 921600
monitor_speed = 115200

; --- Optimize Build ---
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    ; Reduced log level for faster build
    -DCORE_DEBUG_LEVEL=1 
    ; Optional: Uncomment for faster linking (if experiencing slow final steps)
    ; -Wl,--gc-sections
    -O3

; --- Debugging (Only enable when needed) ---
; Comment these out when you are just doing standard development
; debug_tool = esp-builtin
; upload_protocol = esp-builtin

lib_deps =
    devxplained/MAX3010x Sensor Library
    adafruit/Adafruit VCNL4040
    adafruit/Adafruit BusIO
    adafruit/Adafruit LSM6DS